# Generated by Django 5.2.10 on 2026-01-17 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnie', '0001_initial'),
        ('voyages', '0003_add_gare_to_ligne_remove_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du type de dépense (ex: carburant, frais_chauffeur)', max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Nom affiché du type de dépense (ex: Carburant, Frais Chauffeur)', max_length=100, verbose_name='Nom')),
                ('description_obligatoire', models.BooleanField(default=False, help_text='Si coché, une description sera obligatoire lors de la saisie', verbose_name='Description obligatoire')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver pour masquer ce type sans le supprimer', verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les formulaires (0 = premier)", verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_depenses', to='compagnie.compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Type de dépense',
                'verbose_name_plural': 'Types de dépenses',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('compagnie', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, help_text='Montant de la dépense en FCFA', max_digits=10, verbose_name='Montant (FCFA)')),
                ('description', models.TextField(blank=True, help_text='Description détaillée (obligatoire pour certains types)', verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('guichetier', models.ForeignKey(help_text='Guichetier qui a enregistré cette dépense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='voyages.voyage', verbose_name='Voyage')),
                ('type_depense', models.ForeignKey(help_text='Type de dépense (Carburant, Frais chauffeur, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='comptabilite.typedepense', verbose_name='Type de dépense')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_creation'],
            },
        ),
    ]
