# Generated by Django 5.2.10 on 2026-01-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
        ('vehicules', '0004_typereparation_and_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='reparation',
            field=models.ForeignKey(blank=True, help_text='Réparation créée depuis cette dépense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depense_source', to='vehicules.reparationvehicule', verbose_name='Réparation liée'),
        ),
    ]
