# Generated by Django 5.2.10 on 2026-07-24 01:22 (édité à la main : voir
# https://docs.djangoproject.com/en/5.2/howto/writing-migrations/#migrations-that-add-unique-fields
# — le default callable n'est pas appliqué par ligne lors d'un simple AddField sur SQLite).

import uuid
from django.db import migrations, models


def generer_public_id_existants(apps, schema_editor):
    Depense = apps.get_model('comptabilite', 'Depense')
    for depense in Depense.objects.all():
        depense.public_id = uuid.uuid4()
        depense.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_depense_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, help_text='Identifiant stable utilisé pour la synchronisation depuis un poste gare hors-ligne.', verbose_name='Identifiant public'),
        ),
        migrations.RunPython(generer_public_id_existants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='depense',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant stable utilisé pour la synchronisation depuis un poste gare hors-ligne.', unique=True, verbose_name='Identifiant public'),
        ),
        migrations.AddField(
            model_name='depense',
            name='synced_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Renseigné quand cette dépense, saisie sur un poste gare hors-ligne, a été remontée vers le serveur central.', null=True, verbose_name='Synchronisé le'),
        ),
    ]
