# Generated by Django 5.2.10 on 2026-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='chauffeurs/cv/', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='lieu_habitation',
            field=models.CharField(blank=True, max_length=200, verbose_name="Lieu d'habitation"),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants en charge"),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNI'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='personne_urgence',
            field=models.CharField(blank=True, max_length=200, verbose_name="Personne à contacter en cas d'urgence"),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Salaire'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Deuxième téléphone'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='telephone_urgence',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone personne d'urgence"),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='lieu_habitation',
            field=models.CharField(blank=True, max_length=200, verbose_name="Lieu d'habitation"),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants en charge"),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro CNI'),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='personne_urgence',
            field=models.CharField(blank=True, max_length=200, verbose_name="Personne à contacter en cas d'urgence"),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, verbose_name='Situation matrimoniale'),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Deuxième téléphone'),
        ),
        migrations.AddField(
            model_name='convoyeur',
            name='telephone_urgence',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone personne d'urgence"),
        ),
    ]
