# Generated by Django 5.2.10 on 2026-01-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_chauffeur_cv_chauffeur_date_embauche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('pdg', 'PDG'), ('super_admin', 'Super Administrateur'), ('manager', 'Manager'), ('chef_gare', 'Chef de Gare'), ('guichetier', 'Guichetier')], default='guichetier', max_length=20, verbose_name='Rôle'),
        ),
    ]
