# Generated by Django 5.2.10 on 2026-05-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.SlugField(unique=True, verbose_name='Clé')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('icone', models.CharField(default='bi-grid', max_length=100, verbose_name='Icône Bootstrap')),
                ('url_name', models.CharField(max_length=100, verbose_name="Nom d'URL Django")),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='modules_autorises',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_autorises', to='personnel.module', verbose_name='Modules autorisés'),
        ),
    ]
