# Generated by Django 5.2.10 on 2026-06-21 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_populate_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cni', "CNI (Carte Nationale d'Identité)"), ('permis', 'Permis de conduire'), ('certificat_medical', 'Certificat médical'), ('casier_judiciaire', 'Casier judiciaire'), ('contrat', 'Contrat de travail'), ('autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du document')),
                ('fichier', models.FileField(upload_to='chauffeurs/documents/', verbose_name='Fichier')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_chauffeurs_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.chauffeur')),
            ],
            options={
                'verbose_name': 'Document chauffeur',
                'ordering': ['type_document', '-date_ajout'],
            },
        ),
    ]
