# Generated by Django 5.2.10 on 2026-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_type_document_chauffeur_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('pdg', 'PDG'), ('super_admin', 'Super Administrateur'), ('manager', 'Manager'), ('chef_gare', 'Chef de Gare'), ('guichetier', 'Guichetier'), ('agent_courrier', 'Agent Courrier')], default='guichetier', max_length=20, verbose_name='Rôle'),
        ),
    ]
