# Generated by Django 5.2.17 on 2026-09-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('pdg', 'PDG'), ('super_admin', 'Super Administrateur'), ('manager', 'Manager'), ('comptable', 'Comptable'), ('chef_gare', 'Chef de Gare'), ('guichetier', 'Guichetier'), ('agent_courrier', 'Agent Courrier')], default='guichetier', max_length=20, verbose_name='Rôle'),
        ),
    ]
