# Generated by Django 5.2.10 on 2026-02-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='utiliser_souche',
            field=models.BooleanField(default=False, help_text='Si activé, chaque ticket payé sera imprimé avec une souche détachable pour la compagnie', verbose_name='Imprimer avec souche'),
        ),
    ]
