# Generated by Django 5.2.10 on 2026-06-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0002_compagnie_utiliser_souche'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='message_bas_ticket',
            field=models.TextField(blank=True, help_text='Message affiché au bas du ticket client. Ex: Soyez à la gare 30 min avant le départ. BON VOYAGE !', verbose_name='Message bas de ticket'),
        ),
    ]
