# Generated by Django 5.2.10 on 2026-07-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0003_add_message_bas_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='alerte_assurance_active',
            field=models.BooleanField(default=True, verbose_name="L'assurance expire"),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_assurance_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='Alerter X jours avant expiration (assurance)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_assurance_urgent_jours',
            field=models.PositiveIntegerField(default=10, verbose_name='Seuil urgent en jours (assurance)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_carte_grise_active',
            field=models.BooleanField(default=True, verbose_name='La carte grise expire'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_carte_grise_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='Alerter X jours avant expiration (carte grise)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_carte_grise_urgent_jours',
            field=models.PositiveIntegerField(default=10, verbose_name='Seuil urgent en jours (carte grise)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_licence_transport_active',
            field=models.BooleanField(default=True, verbose_name='La licence de transport expire'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_licence_transport_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='Alerter X jours avant expiration (licence transport)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_licence_transport_urgent_jours',
            field=models.PositiveIntegerField(default=10, verbose_name='Seuil urgent en jours (licence transport)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_visite_technique_active',
            field=models.BooleanField(default=True, verbose_name='La visite technique expire'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_visite_technique_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='Alerter X jours avant expiration (visite technique)'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='alerte_visite_technique_urgent_jours',
            field=models.PositiveIntegerField(default=10, verbose_name='Seuil urgent en jours (visite technique)'),
        ),
    ]
