# Generated by Django 5.2.17 on 2026-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0004_compagnie_alerte_assurance_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='fidelite_active',
            field=models.BooleanField(default=False, help_text='Si activé, un voyage offert est accordé aux clients particuliers ayant atteint le seuil.', verbose_name='Activer le programme de fidélité'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='fidelite_active_depuis',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date de la dernière activation du programme — seuls les voyages payés après cette date comptent.', null=True, verbose_name='Fidélité active depuis'),
        ),
        migrations.AddField(
            model_name='compagnie',
            name='fidelite_seuil_voyages',
            field=models.PositiveIntegerField(default=10, help_text='Ex : 10 → le 11ᵉ voyage du client est gratuit, puis le compteur repart.', verbose_name='Nombre de voyages payés pour un voyage offert'),
        ),
    ]
