# Generated by Django 5.2.17 on 2026-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compagnie', '0005_compagnie_fidelite_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, help_text='Optionnel — ex : « Geste commercial », « Tarif étudiant »', max_length=100, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant de la remise (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Remise',
                'verbose_name_plural': 'Remises',
                'ordering': ['ordre', 'montant'],
            },
        ),
    ]
