# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Conakry - Kindia', max_length=200, verbose_name='Nom de la ligne')),
                ('ville_depart', models.CharField(max_length=100, verbose_name='Ville de départ')),
                ('ville_arrivee', models.CharField(max_length=100, verbose_name="Ville d'arrivée")),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance (km)')),
                ('duree_estimee', models.DurationField(blank=True, help_text='Format: HH:MM:SS', null=True, verbose_name='Durée estimée')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compagnie.compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
                'ordering': ['nom'],
                'unique_together': {('ville_depart', 'ville_arrivee', 'compagnie')},
            },
        ),
    ]
