# Generated by Django 5.2.10 on 2026-01-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0001_initial'),
        ('lignes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligne',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ligne',
            name='gare',
            field=models.ForeignKey(blank=True, help_text='Gare de départ de cette ligne', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gares.gare', verbose_name='Gare'),
        ),
        migrations.AlterUniqueTogether(
            name='ligne',
            unique_together={('ville_depart', 'ville_arrivee', 'gare')},
        ),
    ]
