# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('gares', '0001_initial'),
        ('lignes', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('matin', 'Matinée'), ('soir', 'Soir')], max_length=10, verbose_name='Période')),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('jours_actifs', models.JSONField(default=list, help_text='Liste des jours de la semaine où ce programme est actif', verbose_name='Jours actifs')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='destinations.destination', verbose_name='Destination')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='gares.gare', verbose_name='Gare de départ')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='lignes.ligne', verbose_name='Ligne')),
                ('vehicule_defaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='vehicules.vehicule', verbose_name='Véhicule par défaut')),
            ],
            options={
                'verbose_name': 'Programme de départ',
                'verbose_name_plural': 'Programmes de départ',
                'ordering': ['gare', 'heure_depart'],
            },
        ),
    ]
