# Generated by Django 5.2.10 on 2026-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedepart',
            name='numero_depart',
            field=models.PositiveIntegerField(default=1, help_text='Numéro séquentiel du départ (ex: 1, 2, 3...)', verbose_name='Numéro de départ'),
        ),
    ]
