# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gares', '0001_initial'),
        ('lignes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_arrivee', models.CharField(max_length=100, verbose_name="Ville d'arrivée")),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='gares.gare', verbose_name='Gare de départ')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='lignes.ligne', verbose_name='Ligne')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['gare', 'ville_arrivee'],
                'unique_together': {('gare', 'ligne', 'ville_arrivee')},
            },
        ),
    ]
