# Generated by Django 5.2.10 on 2026-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)'),
        ),
    ]
