# Generated by Django 5.2.10 on 2026-07-01 19:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_montant'),
        ('gares', '0002_add_mois_dernier_ticket'),
        ('lignes', '0002_add_gare_to_ligne_remove_destination'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(models.F('gare'), models.F('ligne'), django.db.models.functions.text.Lower('ville_arrivee'), name='destination_unique_gare_ligne_ville_ci', violation_error_message="Une destination existe déjà pour cette gare, cette ligne et cette ville d'arrivée (la casse n'est pas prise en compte)."),
        ),
    ]
