# Generated by Django 5.2.17 on 2026-09-08 16:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_unique_together_and_more'),
        ('gares', '0005_gare_dernier_numero_colis_gare_mois_dernier_colis'),
        ('lignes', '0002_add_gare_to_ligne_remove_destination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destination',
            name='destination_unique_gare_ligne_ville_ci',
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(models.F('gare'), models.F('ligne'), django.db.models.functions.text.Lower('ville_arrivee'), models.F('montant'), name='destination_unique_gare_ligne_ville_montant_ci', violation_error_message="Cette destination existe déjà : même ligne, même gare de départ, même ville d'arrivée et même montant (la casse n'est pas prise en compte)."),
        ),
    ]
