# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Yutong 70 places', max_length=100, verbose_name='Nom du modèle')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('capacite', models.PositiveIntegerField(verbose_name='Capacité (places vendables)')),
                ('disposition_sieges', models.JSONField(default=dict, help_text='Configuration JSON de la disposition des sièges', verbose_name='Disposition des sièges')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de véhicule',
                'verbose_name_plural': 'Modèles de véhicules',
                'ordering': ['marque', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('annee_mise_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de mise en service')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='compagnie.compagnie', verbose_name='Compagnie')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='vehicules.modelevehicule', verbose_name='Modèle')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['immatriculation'],
            },
        ),
    ]
