# Generated by Django 5.2.10 on 2026-01-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='annee_fabrication',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='compagnie_assurance',
            field=models.CharField(blank=True, max_length=100, verbose_name="Compagnie d'assurance"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_assurance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration assurance"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_carte_grise',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration carte grise"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_licence_transport',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration licence de transport"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_expiration_visite_technique',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration visite technique"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_mise_circulation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mise en circulation'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_chassis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de châssis (VIN)'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_boite',
            field=models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20, verbose_name='Type de boîte'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_carburant',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('essence', 'Essence'), ('hybride', 'Hybride'), ('electrique', 'Électrique'), ('gnv', 'GNV (Gaz Naturel)')], max_length=20, verbose_name='Type de carburant'),
        ),
        migrations.CreateModel(
            name='ReparationVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reparation', models.DateField(verbose_name='Date de réparation')),
                ('type_reparation', models.CharField(choices=[('mecanique', 'Mécanique'), ('carrosserie', 'Carrosserie'), ('electrique', 'Électrique'), ('pneumatiques', 'Pneumatiques'), ('revision', 'Révision'), ('autre', 'Autre')], max_length=20, verbose_name='Type de réparation')),
                ('description', models.TextField(verbose_name='Description')),
                ('garage_prestataire', models.CharField(max_length=200, verbose_name='Garage/Prestataire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('pieces_remplacees', models.TextField(blank=True, verbose_name='Pièces remplacées')),
                ('facture', models.FileField(blank=True, null=True, upload_to='reparations/factures/%Y/%m/', verbose_name='Facture/Reçu')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='terminee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparations', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Réparation de véhicule',
                'verbose_name_plural': 'Réparations de véhicules',
                'ordering': ['-date_reparation'],
            },
        ),
    ]
