# Generated by Django 5.2.10 on 2026-01-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0002_vehicule_annee_fabrication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparationvehicule',
            name='facture',
        ),
    ]
