# Generated by Django 5.2.10 on 2026-01-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0004_typereparation_and_migrate_data'),
        ('voyages', '0004_voyage_recette_bagages'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparationvehicule',
            name='creee_depuis_guichet',
            field=models.BooleanField(default=False, help_text='Indique si cette réparation a été créée depuis une dépense de voyage', verbose_name='Créée depuis le guichet'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='voyage_source',
            field=models.ForeignKey(blank=True, help_text='Voyage depuis lequel cette réparation a été créée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparations_generees', to='voyages.voyage', verbose_name='Voyage source'),
        ),
    ]
