# Generated by Django 5.2.10 on 2026-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0005_reparationvehicule_creee_depuis_guichet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparationvehicule',
            name='huile_utilisee',
            field=models.CharField(blank=True, help_text="Type/marque d'huile utilisée (ex: Total Rubia 15W40)", max_length=200, verbose_name='Huile utilisée'),
        ),
        migrations.AddField(
            model_name='reparationvehicule',
            name='intervalle_vidange',
            field=models.PositiveIntegerField(blank=True, choices=[(5000, '5 000 km'), (10000, '10 000 km')], help_text='Kilométrage avant la prochaine vidange', null=True, verbose_name='Intervalle vidange'),
        ),
        migrations.AddField(
            model_name='typereparation',
            name='is_vidange',
            field=models.BooleanField(default=False, help_text='Cocher si ce type de réparation est une vidange (huile + intervalle requis)', verbose_name="C'est une vidange"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='kilometrage_actuel',
            field=models.PositiveIntegerField(default=0, help_text='Compteur km total du véhicule (mis à jour automatiquement à chaque voyage terminé)', verbose_name='Kilométrage actuel'),
        ),
    ]
