# Generated by Django 5.2.10 on 2026-06-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0008_typereparation_necessite_kilometrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='carte_stationnement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Carte de Stationnement'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_carte_grise',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Carte Grise'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='numero_ordre',
            field=models.CharField(blank=True, help_text="Numéro d'arrivage du véhicule (ex: 01, 05, 30). Unique.", max_length=10, unique=True, verbose_name="N° d'ordre"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='patente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='ligneintervention',
            name='huile_utilisee',
            field=models.CharField(blank=True, help_text="Type/marque d'huile (ex: Total Rubia 15W40) — pour les vidanges", max_length=200, verbose_name='Huile utilisée'),
        ),
        migrations.AlterField(
            model_name='ligneintervention',
            name='intervalle_km',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométrage avant la prochaine intervention de ce type', null=True, verbose_name='Intervalle km'),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='date_reparation',
            field=models.DateField(verbose_name="Date d'entrée au garage"),
        ),
        migrations.AlterField(
            model_name='reparationvehicule',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='typereparation',
            name='intervalle_km_defaut',
            field=models.PositiveIntegerField(blank=True, help_text='Si renseigné, ce type sera suivi par kilométrage (ex: 10000 pour une vidange tous les 10 000 km)', null=True, verbose_name='Intervalle km (défaut)'),
        ),
        migrations.AlterField(
            model_name='typereparation',
            name='is_vidange',
            field=models.BooleanField(default=False, help_text="Cocher uniquement si c'est une vidange d'huile — affiche le champ huile utilisée", verbose_name="C'est une vidange (huile requise)"),
        ),
        migrations.AlterField(
            model_name='typereparation',
            name='necessite_kilometrage',
            field=models.BooleanField(default=False, help_text="Cocher si ce type d'intervention nécessite de saisir le km au compteur (courroie, vidange, freins…)", verbose_name='Nécessite saisie kilométrage'),
        ),
    ]
