# Generated by Django 5.2.17 on 2026-09-07 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0009_add_numero_ordre_and_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPieceGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur / mécano')),
                ('libelle', models.CharField(help_text='Ex : jeu de plaquettes + 2 disques avant', max_length=255, verbose_name='Pièces prises à crédit')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('date_achat', models.DateField(verbose_name='Date de prise à crédit')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé')], default='en_cours', editable=False, max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_pieces_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_pieces', to='vehicules.reparationvehicule', verbose_name='Réparation')),
            ],
            options={
                'verbose_name': 'Crédit pièces (garage)',
                'verbose_name_plural': 'Crédits pièces (garage)',
                'ordering': ['-date_achat', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='VersementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_versement', models.DateField(verbose_name='Date du versement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant versé (FCFA)')),
                ('moyen_paiement', models.CharField(choices=[('cash', 'Cash'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('virement', 'Virement')], default='cash', max_length=20, verbose_name='Moyen de paiement')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='vehicules.creditpiecegarage', verbose_name='Crédit pièces')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_credit_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Versement crédit garage',
                'verbose_name_plural': 'Versements crédit garage',
                'ordering': ['date_versement', 'date_creation'],
            },
        ),
    ]
