# Generated by Django 5.2.17 on 2026-09-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0011_typedocumentvehicule_documentvehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='versementcredit',
            name='numero_beneficiaire',
            field=models.CharField(blank=True, help_text='Numéro mobile money ayant reçu le paiement', max_length=30, verbose_name='Numéro du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='versementcredit',
            name='reference_transaction',
            field=models.CharField(blank=True, help_text='Code de transaction (Wave/Orange/MTN/Moov) ou référence du virement — preuve du paiement', max_length=100, verbose_name='Référence de la transaction'),
        ),
    ]
