# Generated by Django 5.2.10 on 2026-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Numéro du ticket')),
                ('client_nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_telephone', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('numero_siege', models.PositiveIntegerField(verbose_name='Numéro de siège')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (GNF)')),
                ('statut', models.CharField(choices=[('reserve', 'Réservé'), ('paye', 'Payé')], default='reserve', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
