# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billets', '0001_initial'),
        ('voyages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='guichetier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets_vendus', to=settings.AUTH_USER_MODEL, verbose_name='Guichetier'),
        ),
        migrations.AddField(
            model_name='billet',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='voyages.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterUniqueTogether(
            name='billet',
            unique_together={('voyage', 'numero_siege')},
        ),
    ]
