# Generated by Django 5.2.10 on 2026-01-16 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0002_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='destinations.destination', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)'),
        ),
    ]
