# Generated by Django 5.2.10 on 2026-01-23 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0004_billet_moyen_paiement'),
        ('voyages', '0004_voyage_recette_bagages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='date_report',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du report'),
        ),
        migrations.AddField(
            model_name='billet',
            name='guichetier_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Guichetier ayant effectué le report'),
        ),
        migrations.AddField(
            model_name='billet',
            name='motif_report',
            field=models.TextField(blank=True, verbose_name='Motif du report'),
        ),
        migrations.AddField(
            model_name='billet',
            name='reporte_vers_billet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billet_origine', to='billets.billet', verbose_name='Reporté vers le billet'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='statut',
            field=models.CharField(choices=[('reserve', 'Réservé'), ('paye', 'Payé'), ('reporte', 'Reporté')], default='reserve', max_length=10, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='HistoriqueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_siege', models.PositiveIntegerField(verbose_name='Ancien siège')),
                ('nouveau_siege', models.PositiveIntegerField(verbose_name='Nouveau siège')),
                ('motif', models.TextField(verbose_name='Motif du report')),
                ('date_report', models.DateTimeField(auto_now_add=True, verbose_name='Date du report')),
                ('ancien_billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_ancien', to='billets.billet', verbose_name='Ancien billet')),
                ('ancien_voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_depuis', to='voyages.voyage', verbose_name='Ancien voyage')),
                ('guichetier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Guichetier')),
                ('nouveau_billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_nouveau', to='billets.billet', verbose_name='Nouveau billet')),
                ('nouveau_voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_vers', to='voyages.voyage', verbose_name='Nouveau voyage')),
            ],
            options={
                'verbose_name': 'Historique de report',
                'verbose_name_plural': 'Historiques de reports',
                'ordering': ['-date_report'],
            },
        ),
    ]
