# Generated by Django 5.2.10 on 2026-03-14 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0005_billet_date_report_billet_guichetier_report_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets', to='clients.client', verbose_name='Client'),
        ),
    ]
