# Generated by Django 5.2.10 on 2026-06-21 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0006_add_client_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='numero_siege',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de siège'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='statut',
            field=models.CharField(choices=[('reserve', 'Réservé'), ('paye', 'Payé'), ('reporte', 'Reporté'), ('rembourse', 'Remboursé')], default='reserve', max_length=10, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif du remboursement')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant à rembourser')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('billet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_remboursement', to='billets.billet', verbose_name='Billet')),
                ('demandee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_remboursement_creees', to=settings.AUTH_USER_MODEL, verbose_name='Demandée par')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'verbose_name_plural': 'Demandes de remboursement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
