# Generated by Django 5.2.10 on 2026-06-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0007_add_rembourse_statut_and_demande_remboursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='statut',
            field=models.CharField(choices=[('reserve', 'Réservé'), ('paye', 'Payé'), ('gratuit_en_attente', 'Gratuit (en attente)'), ('gratuit', 'Gratuit'), ('reporte', 'Reporté'), ('rembourse', 'Remboursé')], default='reserve', max_length=25, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='DemandeTicketGratuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire (refus)')),
                ('billet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_gratuit', to='billets.billet', verbose_name='Billet')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_gratuit_creees', to=settings.AUTH_USER_MODEL, verbose_name='Demandée par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_gratuit_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traitée par')),
            ],
            options={
                'verbose_name': 'Demande de ticket gratuit',
                'verbose_name_plural': 'Demandes de tickets gratuits',
                'ordering': ['-date_demande'],
            },
        ),
    ]
