# Generated by Django 5.2.10 on 2026-07-03 15:59
# Modifié à la main : ajout du champ en 3 temps (voir clients/migrations/0002).

import uuid
from django.db import migrations, models


def generer_public_id_distincts(apps, schema_editor):
    Billet = apps.get_model('billets', 'Billet')
    for billet in Billet.objects.all():
        billet.public_id = uuid.uuid4()
        billet.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0008_add_gratuit_statut_and_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de billets.", null=True, verbose_name='Identifiant public'),
        ),
        migrations.RunPython(generer_public_id_distincts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='billet',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de billets.", unique=True, verbose_name='Identifiant public'),
        ),
    ]
