# Generated by Django 5.2.17 on 2026-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0010_billet_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='statut',
            field=models.CharField(choices=[('reserve', 'Réservé'), ('paye', 'Payé'), ('gratuit_en_attente', 'Gratuit (en attente)'), ('gratuit', 'Gratuit'), ('fidelite', 'Fidélité (offert)'), ('reporte', 'Reporté'), ('rembourse', 'Remboursé')], default='reserve', max_length=25, verbose_name='Statut'),
        ),
    ]
