# Generated by Django 5.2.17 on 2026-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0011_alter_billet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='remise',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Réduction accordée sur ce billet (choisie parmi les remises configurées).', max_digits=10, verbose_name='Remise (FCFA)'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='montant',
            field=models.DecimalField(decimal_places=0, help_text='Montant réellement encaissé = tarif de la destination − remise.', max_digits=10, verbose_name='Montant (FCFA)'),
        ),
    ]
