# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compagnie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la gare')),
                ('code', models.CharField(help_text='Code unique pour la numérotation des tickets (ex: CKY, KND)', max_length=10, unique=True, verbose_name='Code')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dernier_numero_ticket', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro de ticket')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gares', to='compagnie.compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Gare',
                'verbose_name_plural': 'Gares',
                'ordering': ['nom'],
            },
        ),
    ]
