# Generated by Django 5.2.10 on 2026-01-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gare',
            name='mois_dernier_ticket',
            field=models.CharField(blank=True, default='', help_text='Format YYYYMM pour la réinitialisation mensuelle', max_length=6, verbose_name='Mois du dernier ticket'),
        ),
    ]
