# Generated by Django 5.2.10 on 2026-07-24 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0002_add_mois_dernier_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GareSyncToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_utilisation', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('gare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_token', to='gares.gare', verbose_name='Gare')),
            ],
            options={
                'verbose_name': 'Jeton de synchronisation gare',
                'verbose_name_plural': 'Jetons de synchronisation gare',
            },
        ),
    ]
