# Generated by Django 5.2.10 on 2026-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0003_garesynctoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='gare',
            name='imprimante_largeur_caracteres',
            field=models.PositiveIntegerField(default=42, help_text='42 convient à la plupart des imprimantes thermiques 80mm.', verbose_name='Largeur du ticket (caractères)'),
        ),
        migrations.AddField(
            model_name='gare',
            name='imprimante_nom',
            field=models.CharField(blank=True, default='', help_text='Nom exact tel qu\'affiché dans "Périphériques et imprimantes" sur ce poste.', max_length=100, verbose_name="Nom de l'imprimante (Windows)"),
        ),
    ]
