# Generated by Django 5.2.10 on 2026-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0004_gare_imprimante_largeur_caracteres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gare',
            name='dernier_numero_colis',
            field=models.PositiveIntegerField(default=0, verbose_name='Dernier numéro de colis'),
        ),
        migrations.AddField(
            model_name='gare',
            name='mois_dernier_colis',
            field=models.CharField(blank=True, default='', help_text='Format YYYYMM pour la réinitialisation mensuelle', max_length=6, verbose_name='Mois du dernier colis'),
        ),
    ]
