# Generated by Django 5.2.10 on 2026-07-24 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gares', '0003_garesynctoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('push', 'Push (gare → central)'), ('pull', 'Pull (central → gare)')], max_length=10, verbose_name='Sens')),
                ('statut', models.CharField(choices=[('ok', 'Réussi'), ('partiel', 'Réussi avec erreurs'), ('erreur', 'Échoué')], default='ok', max_length=10, verbose_name='Statut')),
                ('nb_enregistrements', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('detail', models.TextField(blank=True, verbose_name='Détail / erreurs')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='gares.gare', verbose_name='Gare')),
            ],
            options={
                'verbose_name': 'Journal de synchronisation',
                'verbose_name_plural': 'Journaux de synchronisation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
