# Generated by Django 5.2.10 on 2026-07-03 15:40
# Modifié à la main : ajout du champ en 3 temps pour rester sûr sur une table
# non vide (un défaut "callable" appliqué en une seule opération AddField+unique
# assignerait la même valeur à toutes les lignes existantes en SQL brut).

import uuid
from django.db import migrations, models


def generer_public_id_distincts(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.all():
        client.public_id = uuid.uuid4()
        client.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de clients.", null=True, verbose_name='Identifiant public'),
        ),
        migrations.RunPython(generer_public_id_distincts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='client',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de clients.", unique=True, verbose_name='Identifiant public'),
        ),
    ]
