# Generated by Django 5.2.10 on 2026-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='numero_cni',
            field=models.CharField(blank=True, help_text="Mémorisé dès qu'il est saisi une première fois (ex: retrait de colis) pour être réutilisé automatiquement ensuite.", max_length=50, verbose_name='N° CNI'),
        ),
    ]
