# Generated by Django 5.2.17 on 2026-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_numero_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categorie',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('societe', 'Société')], db_index=True, default='particulier', help_text="« Société » = structure qui nous envoie des passagers. Le programme de fidélité ne s'applique qu'aux « Particulier ».", max_length=15, verbose_name='Catégorie'),
        ),
    ]
