# Generated by Django 5.2.10 on 2026-08-14 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_synced_at'),
        ('compagnie', '0004_compagnie_alerte_assurance_active_and_more'),
        ('gares', '0005_gare_dernier_numero_colis_gare_mois_dernier_colis'),
        ('voyages', '0007_voyage_synced_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de colis.", unique=True, verbose_name='Identifiant public')),
                ('code_colis', models.CharField(max_length=30, unique=True, verbose_name='Code colis')),
                ('code_retrait', models.CharField(max_length=10, verbose_name='Code de retrait')),
                ('expediteur_nom', models.CharField(max_length=200, verbose_name="Nom de l'expéditeur")),
                ('expediteur_telephone', models.CharField(max_length=20, verbose_name="Téléphone de l'expéditeur")),
                ('destinataire_nom', models.CharField(max_length=200, verbose_name='Nom du destinataire')),
                ('destinataire_telephone', models.CharField(max_length=20, verbose_name='Téléphone du destinataire')),
                ('description', models.TextField(blank=True, verbose_name='Description du contenu')),
                ('valeur_declaree', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Valeur déclarée (FCFA)')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('qui_paie', models.CharField(choices=[('expediteur', 'Expéditeur (port payé)'), ('destinataire', 'Destinataire (port dû)')], default='expediteur', max_length=15, verbose_name='Qui paie')),
                ('moyen_paiement', models.CharField(choices=[('cash', 'Cash'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money')], default='cash', max_length=20, verbose_name='Moyen de paiement')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], default='enregistre', max_length=15, verbose_name='Statut')),
                ('piece_identite_retrait', models.CharField(blank=True, help_text='Type et numéro (ex: CNI 123456789)', max_length=100, verbose_name="Pièce d'identité présentée au retrait")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_chargement', models.DateTimeField(blank=True, null=True, verbose_name='Date de chargement')),
                ('date_arrivee', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('date_limite_retrait', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de retrait')),
                ('date_retrait', models.DateTimeField(blank=True, null=True, verbose_name='Date de retrait')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_recus', to='clients.client', verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_envoyes', to='clients.client', verbose_name='Expéditeur')),
                ('gare_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_destination', to='gares.gare', verbose_name='Gare de destination')),
                ('gare_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_origine', to='gares.gare', verbose_name="Gare d'origine")),
                ('guichetier_chargement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_charges', to=settings.AUTH_USER_MODEL, verbose_name='Chargé par')),
                ('guichetier_enregistrement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('guichetier_retrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_retires', to=settings.AUTH_USER_MODEL, verbose_name='Retiré par')),
                ('voyage', models.ForeignKey(blank=True, help_text='Renseigné uniquement au chargement — un lien logistique, jamais financier (la recette courrier reste indépendante de la recette du voyage).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='voyages.voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], max_length=15, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], max_length=15, verbose_name='Nouveau statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='courrier.colis', verbose_name='Colis')),
                ('gare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gares.gare', verbose_name='Gare')),
            ],
            options={
                'verbose_name': 'Historique de statut colis',
                'verbose_name_plural': 'Historiques de statut colis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TypeColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('tarif_indicatif', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif indicatif (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_colis', to='compagnie.compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Type de colis',
                'verbose_name_plural': 'Types de colis',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('compagnie', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='colis',
            name='type_colis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='courrier.typecolis', verbose_name='Type de colis'),
        ),
    ]
