# Generated by Django 5.2.10 on 2026-08-14 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_numero_cni'),
        ('courrier', '0003_seed_types_colis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='colis',
            name='guichetier_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_receptionnes', to=settings.AUTH_USER_MODEL, verbose_name='Réceptionné par'),
        ),
        migrations.AddField(
            model_name='colis',
            name='retirant',
            field=models.ForeignKey(blank=True, help_text="Personne qui s'est effectivement présentée au retrait — le destinataire, ou un mandataire.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_retires_pour', to='clients.client', verbose_name='Retirant'),
        ),
        migrations.AddField(
            model_name='colis',
            name='retirant_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du retirant'),
        ),
        migrations.AddField(
            model_name='colis',
            name='retirant_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone du retirant'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='piece_identite_retrait',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° CNI présenté au retrait'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('receptionne', 'Réceptionné'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], default='enregistre', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historiquestatutcolis',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('receptionne', 'Réceptionné'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], max_length=15, verbose_name='Ancien statut'),
        ),
        migrations.AlterField(
            model_name='historiquestatutcolis',
            name='nouveau_statut',
            field=models.CharField(choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé'), ('receptionne', 'Réceptionné'), ('retire', 'Retiré'), ('non_reclame', 'Non réclamé'), ('retourne', "Retourné à l'expéditeur"), ('annule', 'Annulé')], max_length=15, verbose_name='Nouveau statut'),
        ),
    ]
