# Generated by Django 5.2.10 on 2026-01-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('gares', '0001_initial'),
        ('lignes', '0001_initial'),
        ('personnel', '0001_initial'),
        ('programmes', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('periode', models.CharField(choices=[('matin', 'Matinée'), ('soir', 'Soir')], max_length=10, verbose_name='Période')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='programme', max_length=20, verbose_name='Statut')),
                ('cree_automatiquement', models.BooleanField(default=False, verbose_name='Créé automatiquement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='personnel.chauffeur', verbose_name='Chauffeur')),
                ('convoyeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='personnel.convoyeur', verbose_name='Convoyeur')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='destinations.destination', verbose_name='Destination')),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='gares.gare', verbose_name='Gare de départ')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='lignes.ligne', verbose_name='Ligne')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages_generes', to='programmes.programmedepart', verbose_name='Programme source')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='vehicules.vehicule', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'ordering': ['-date_depart', 'heure_depart'],
                'unique_together': {('gare', 'ligne', 'date_depart', 'heure_depart', 'periode')},
            },
        ),
    ]
