# Generated by Django 5.2.10 on 2026-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gares', '0001_initial'),
        ('lignes', '0001_initial'),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voyage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='voyage',
            name='numero_depart',
            field=models.PositiveIntegerField(default=1, help_text='Numéro séquentiel du départ (ex: 1, 2, 3...)', verbose_name='Numéro de départ'),
        ),
        migrations.AlterUniqueTogether(
            name='voyage',
            unique_together={('gare', 'ligne', 'date_depart', 'heure_depart', 'periode', 'numero_depart')},
        ),
    ]
