# Generated by Django 5.2.10 on 2026-01-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_alter_voyage_unique_together_voyage_numero_depart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='destination',
        ),
    ]
