# Generated by Django 5.2.10 on 2026-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_add_gare_to_ligne_remove_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='recette_bagages',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant total des bagages pour ce voyage', max_digits=10, verbose_name='Recette Bagages (FCFA)'),
        ),
    ]
