# Generated by Django 5.2.10 on 2026-06-20 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0006_add_client_fk'),
        ('voyages', '0004_voyage_recette_bagages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignationSiege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_siege', models.PositiveIntegerField(verbose_name='Ancien siège')),
                ('nouveau_siege', models.PositiveIntegerField(verbose_name='Nouveau siège')),
                ('date_reassignation', models.DateTimeField(auto_now_add=True)),
                ('billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignations', to='billets.billet', verbose_name='Billet')),
                ('effectuee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectuée par')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignations', to='voyages.voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Réassignation de siège',
                'verbose_name_plural': 'Réassignations de sièges',
                'ordering': ['-date_reassignation'],
            },
        ),
    ]
