# Generated by Django 5.2.10 on 2026-07-03 15:44
# Modifié à la main : ajout du champ en 3 temps (voir clients/migrations/0002).

import uuid
from django.db import migrations, models


def generer_public_id_distincts(apps, schema_editor):
    Voyage = apps.get_model('voyages', 'Voyage')
    for voyage in Voyage.objects.all():
        voyage.public_id = uuid.uuid4()
        voyage.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_add_reassignation_siege'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de voyages.", null=True, verbose_name='Identifiant public'),
        ),
        migrations.RunPython(generer_public_id_distincts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='voyage',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Utilisé dans les URL à la place de l'identifiant interne, pour ne pas exposer le volume de voyages.", unique=True, verbose_name='Identifiant public'),
        ),
    ]
