# Generated by Django 5.2.10 on 2026-07-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_voyage_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='synced_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Renseigné quand ce voyage, créé sur un poste gare hors-ligne, a été remonté vers le serveur central.', null=True, verbose_name='Synchronisé le'),
        ),
    ]
